import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Posts as PostsComponents } from "../../components/Posts";
import { Header } from "../../components/Header";

const Posts = (props) => {
  return (
    <>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PostsComponents />
      <Footer />
    </>
  );
};
export default Posts;
