import Head from "next/head";
import { Footer } from "../../../components/Footer";
import { Header } from "../../../components/Header";
import { useUser } from "../../../hooks/useUser";
import { User } from "@/components/User";

const UsersId = () => {
  const { post, user, error, isLoading } = useUser();

  return (
    <>
      <Head>
        <title>{user?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <User />
      <Footer />
    </>
  );
};
export default UsersId;
