import Head from "next/head";
import { Footer } from "@/components/Footer";
import { Main } from "@/components/Main";
import styles from "@/styles/Home.module.css";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from "@/components/Header/index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Index = () => {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Next.jsで学ぶReact講座</h1>
      <p>JSON PlaceholderのAPIを叩きます</p>
    </>
  );
};

export default Index;
