import Head from "next/head";
import { Footer } from "../../../components/Footer";
import { Header } from "../../../components/Header";
import { useRouter } from "next/router";

const PostId = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <ol>test post{router.query.id}</ol>
      <Footer />
    </>
  );
};
export default PostId;
