import Head from "next/head";
import { Footer } from "../../../components/Footer";
import { Header } from "../../../components/Header";
import { usePost } from "../../../hooks/usePost";
import { Post } from "@/components/Post";

const PostId = () => {
  const { post, user, error, isLoading } = usePost();

  console.log({ post, user, error, isLoading });

  return (
    <>
      <Head>
        <title>{post?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Post />
      <Footer />
    </>
  );
};
export default PostId;
