import { Footer } from "../../../components/Footer";
import { Header } from "../../../components/Header";
import { Comment } from "../../../components/Comment";
import Head from "next/head";
import styles from "../../../styles/Children.module.css";
import { useComment } from "../../../hooks/useComment";

const CommentId = () => {
  const comment = useComment();
  return (
    <div className={styles.container}>
      <Head>
        <title>{comment?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Comment />
      <Footer />
    </div>
  );
};

export default CommentId;
