import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Users as UsersComponents } from "../../components/Users";
import { Header } from "../../components/Header";

const Users = (props) => {
  return (
    <>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <UsersComponents />
      <Footer />
    </>
  );
};
export default Users;
