import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import Head from "next/head";
import { Comments as CommentsComponet } from "../../components/Comments";

const Commments = () => {
  return (
    <>
      <Head>
        <title>Users Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CommentsComponet />
      <Footer />
    </>
  );
};

export default Commments;
